### ISSUE TITLE
Wireless, Wi-Fi, rum(4), urtw(4): no wlan0 unless the savecache service is deleted from the shutdown runlevel before the start of the computer

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#252] opened 2016-12-27 15:16 UTC
Whilst troubleshooting a different issue involving shutdown, I experimented with deletion of the `savecache` service. 

Without that service at the `shutdown` runlevel, it seemed easier to make reliable use, with TrueOS Desktop, of a USB network adapter that is supported as a wireless network interface by FreeBSD 12.0-CURRENT.

Today I performed more focused testing. From the attached file: 

```
Dec 27 08:49:29  shutdown: reboot by bbsadmin-l: 
Dec 27 08:50:39  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 09:07:11  shutdown: reboot by bbsadmin-l: 
Dec 27 09:08:22  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 09:15:19  shutdown: reboot by bbsadmin-l: 
Dec 27 09:16:30  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 09:19:26  shutdown: reboot by bbsadmin-l: 
Dec 27 09:20:35  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 09:39:53  shutdown: reboot by bbsadmin-l: 
Dec 27 09:41:04  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 09:43:52  shutdown: reboot by bbsadmin-l: 
Dec 27 09:45:10  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 10:00:33  shutdown: reboot by bbsadmin-l: 
Dec 27 10:01:43  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 10:04:25  shutdown: reboot by bbsadmin-l: 
Dec 27 10:05:36  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 10:12:22  shutdown: reboot by bbsadmin-l: 
Dec 27 10:13:33  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 10:23:42  shutdown: reboot by bbsadmin-l: 
Dec 27 10:24:53  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 10:29:39  shutdown: reboot by bbsadmin-l: 
Dec 27 10:30:50  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 11:21:45  shutdown: reboot by bbsadmin-l: 
Dec 27 11:22:55  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 11:32:27  shutdown: reboot by bbsadmin-l: 
Dec 27 11:33:39  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 11:42:48  shutdown: reboot by bbsadmin-l: 
Dec 27 11:43:59  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 11:57:31  shutdown: reboot by bbsadmin-l: 
Dec 27 11:58:42  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 12:01:42  shutdown: reboot by bbsadmin-l: 
Dec 27 12:02:52  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 12:11:32  shutdown: reboot by bbsadmin-l: 
Dec 27 12:12:43  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 12:20:32  shutdown: reboot by bbsadmin-l: 
Dec 27 12:21:41  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 12:23:15  shutdown: reboot by bbsadmin-l: 
Dec 27 12:24:25  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 12:26:50  shutdown: reboot by bbsadmin-l: 
Dec 27 12:28:01  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 12:32:54  shutdown: reboot by bbsadmin-l: 
Dec 27 12:34:04  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 13:09:15  shutdown: reboot by bbsadmin-l: 
Dec 27 13:10:29  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 13:14:15  shutdown: reboot by bbsadmin-l: 
Dec 27 13:15:28  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 13:59:22  shutdown: reboot by bbsadmin-l: 
Dec 27 14:00:32  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 14:08:03  shutdown: reboot by bbsadmin-l: 
Dec 27 14:09:14  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 14:10:23  shutdown: reboot by bbsadmin-l: 
Dec 27 14:11:33  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 14:13:46  shutdown: reboot by bbsadmin-l: 
Dec 27 14:15:02  syslogd: kernel boot file is /boot/kernel/kernel
Dec 27 14:16:06  shutdown: reboot by bbsadmin-l: 
Dec 27 14:17:17  syslogd: kernel boot file is /boot/kernel/kernel
```

In the first twenty-something cases, without `savecache`, a login to a desktop environment found an icon for `wlan0`. 

The reboot at 14:13:46 was preceded by experimental reintroduction of the `savecache` service. Critically: 

- the subsequent boot at 14:15:02 did **not** have `wlan0`. 

The reboot at 14:16:06 was preceded by deletion of the `savecache` service and I'm now using the device at wlan0 without difficulty. 

[terminal output.txt](https://github.com/trueos/trueos-core/files/674283/terminal.output.txt)

## Environment

- MacBookPro11,2
- `FreeBSD 12.0-CURRENT #11 8b9df91(drm-next-4.7): Sat Dec 24 15:17:28 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC`
- [D-Link DWL-G122 rev C1](http://www.dlink.com/uk/en/support/product/dwl-g122-wireless-g-usb-dongle)

**Comment by grahamperrin** [comment] 2016-12-27 17:18
Hmm, sorry, where (if anywhere) should I find `rum0` in the file system? 

I imagined that as a device, it should be at `/dev/`, hence the change of title here after performing a further test with the service deleted before a restart of the OS: 

```
bbsadmin-l@momh167-gjp4-macbookpro112-trueos ~> date ; uptime ; uname -v
Tue 27 Dec 2016 15:41:58 GMT
 3:41p.m.  up 3 mins, 1 users, load averages: 0.94, 0.54, 0.23
FreeBSD 12.0-CURRENT #11 8b9df91(drm-next-4.7): Sat Dec 24 15:17:28 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
bbsadmin-l@momh167-gjp4-macbookpro112-trueos ~> ls -dl /dev/r*
crw-r--r--  1 root  wheel  0x7 27 Dec 15:39 /dev/random
dr-xr-xr-x  2 root  wheel  512 27 Dec 15:38 /dev/reroot
bbsadmin-l@momh167-gjp4-macbookpro112-trueos ~> rc-update
                  abi | boot                                   
            adjkerntz | boot                                   
            automount |      default                           
             bootmisc | boot                                   
               bridge | boot                                   
                 cron | boot                                   
         cups_browsed |      default                           
                cupsd |      default                           
                 dbus |      default                           
                 devd | boot                                   
               dumpon | boot                                   
                 fsck | boot                                   
               hostid | boot                                   
             hostname | boot                                   
                 ipfw | boot                                   
                local |      default nonetwork                 
           localmount | boot                                   
                lockd |      default                           
             loopback | boot                                   
              modules | boot                                   
                 motd | boot                                   
               moused |      default                           
             netmount |      default                           
              network | boot                                   
            newsyslog | boot                                   
             openntpd |      default                           
                 pcdm |      default                           
                 root | boot                                   
              rpcbind |      default                           
            savecache |                        shutdown        
             savecore | boot                                   
                 sshd |      default                           
                statd |      default                           
          staticroute | boot                                   
                 swap | boot                                   
               sysadm |      default                           
              syscons | boot                                   
               sysctl | boot                                   
              syslogd | boot                                   
           trueosinit |      default                           
              urandom | boot                                   
                  zfs | boot default                           
                 zvol | boot                                   
bbsadmin-l@momh167-gjp4-macbookpro112-trueos ~> sudo rc-update remove savecache shutdown
Password:
 * rc-update: invalid command `remove'
bbsadmin-l@momh167-gjp4-macbookpro112-trueos ~> sudo rc-update delete savecache shutdown
 * service savecache removed from runlevel shutdown
bbsadmin-l@momh167-gjp4-macbookpro112-trueos ~> 
```

Now I realise, with the device working for `wlan0`, there's still no `rum0` at `/dev/`.

## rc.conf

```
$ cat /etc/rc.conf
rc_parallel="NO"
rc_logger="YES"
rc_log_path="/var/log/rc.log"
linux_enable="YES"
# Auto-Enabled NICs from pc-sysinstall
ifconfig_ue0="DHCP"
# Auto-Enabled NICs from pc-sysinstall
ifconfig_ue0_ipv6="inet6 accept_rtadv"
hostname="momh167-gjp4-macbookpro112-trueos.university.brighton.ac.uk"
kldload_i915kms="i915kms"
zfs_enable="YES"
sshd_enable="YES"
wlans_rum0="wlan0"
ifconfig_wlan0="WPA DHCP"
$ 
```

**Comment by grahamperrin** [comment] 2016-12-27 18:58
https://www.freebsd.org/cgi/man.cgi?query=rum&sektion=4&manpath=FreeBSD+12-current

**Comment by pkgdemon** [comment] 2016-12-27 20:01
I think I may be seeing this regression as well but with a usb ethernet ums0.  I will try removing savecache from shutdown to see if this fixes.

**Comment by pkgdemon** [comment] 2016-12-27 22:13
Ok removing savecore doesn't fix my issue.  My issue was just the fact that devd is no longer loading the module.  @grahamperrin I don't believe wireless devices ever show in in /dev/, or that anything is created in the filesystem as it is on Linux.  I know `sysctl -b net.wlan.devices` can be used to see wireless devices if they have a module loaded.  Otherwise ```pciconf -lv``` may be of some use just to see if the hardware is detected at all even without a module loaded.

**Comment by grahamperrin** [comment] 2016-12-30 02:57
```
$ uname -v
FreeBSD 12.0-CURRENT #12 5ef9376(drm-next-4.7): Thu Dec 29 16:26:36 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$
```

For consideration: [D-Link DWL-G122 rev C1 now recognised (wlan0) at a MacBookPro8,2](https://discourse.trueos.org/t/wireless-networking-with-rum-4-and-a-d-link-device-for-wlan0/459/7?u=grahamperrin)

> … **not** recommended, known to cause trouble, but for the moment I'm most interested in Internet connectivity. …

**Comment by pkgdemon** [comment] 2016-12-31 15:46
Does the exstension cable include a hub as well?

**Comment by grahamperrin** [comment] 2016-12-31 16:44
No, just a simple cable. Maybe one metre long. White. No manufacturer's brand but it's well-manufactured. 

## MacBookPro5,2

https://discourse.trueos.org/t/wireless-networking-with-rum-4-and-a-d-link-device-for-wlan0/459/6?u=grahamperrin reminds me that around 2016-12-27 (four days ago) I had this Mac working with a non-encrypted installation of TrueOS Desktop on a USB flash drive. 

A few hours ago I overwrote that with with an encrypted installation, updated to `FreeBSD 12.0-CURRENT #12 5ef9376(drm-next-4.7): Thu Dec 29 16:26:36 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC, booted five or six times with required lines in `/etc/rc.conf`: 

- none of the boots resulted in `wlan0`.

I deleted `savecache` from runlevel `shutdown`, commanded `shutdown -r now` and now: 

- wlan0 is present and working. 

(Stage two of an update routine began a couple of minutes ago, I guess that it'll be 5ef9376 again with changes in some areas.)

**Comment by pkgdemon** [comment] 2016-12-31 16:52
Does encrypted vs non encrypted make the difference?  Or is it running TrueOS from a USB flash drive vs internal drive?

**Comment by pkgdemon** [comment] 2016-12-31 16:53
Or is it the cable?  Need more clarity on this one.

**Comment by grahamperrin** [comment] 2016-12-31 17:15
One memorable difference: tl;dr the earlier, non-encrypted installation was fresh when the USB flash drive was at an HP desktop. I made that an opportunity to subsequently learn, re-learn how to manually add support when moving an installation from one hardware environment to another. Point of reference https://discourse.trueos.org/t/macbookpro5-2-17-macbook-pro-2009/479 but I'm carefully **not** quoting from that opening post; most relevant to this issue is: 

- at some point during that learning experience, I probably did quietly, routinely delete the `savecache` service, for the D-Link to be usable in that environment. 

----

Relevant from [the second post](https://discourse.trueos.org/t/macbookpro5-2-17-macbook-pro-2009/479/2?u=grahamperrin) in that topic: 

> I performed a fresh, encrypted installation to the same USB flash drive, this time with the drive connected to the MacBookPro5,2. …

The D-Link device almost certainly was **not** present at that time of freshness. That's almost certain because: 

- this Mac's three ports are in close proximity to each other
- the USB flash drive that contained the installer is a Kingston DataTraveler G3, the physical size of which prevents use of any adjacent port
- with the middle port inaccessible, the USB flash drive that received the installation (Kingston DataTraveler G4, 16 GB) was at the third port. 

That's potentially a lot to take in :-) so if anything remains unclear, just say. 

## Next steps

### On one hand

I might try this USB flash drive with the D-Link device at something other than an Apple notebook; tell whether the run of `savecache` can be troublesome with another brand of computer. If I do this, I'll probably target an old (c. 2007) but predictable Ergo Vista 621. 

### On the other hand

Should I defer broader testing until after the 'new' _FreeBSD netif_ flavour of OpenRC `network` service is in the mix? 

(https://gitter.im/trueos/troubleshooting?at=5867e1dcd99b1dd03d2e7c74 there's a question about distinguishing between flavours of the service.) 

Thanks

**Comment by pkgdemon** [comment] 2016-12-31 19:39
Yeah this is way too much information to take in.  I only need to know the answers to the specific questions I asked above.  Does that require retesting on your end?  Or can you just narrow down what you are able to without a reinstall if that is the case?  Namely is it the usb extension cable to start?

**Comment by grahamperrin** [comment] 2016-12-31 21:13
Where the extension cable was required, I'd like to retest to be certain **however**: if I do so without knowing whether it's the new or old flavour of `network` service, I'll become confused. 

Results from today's test with the MacBookPro5,2, which does not require an extension cable, seem reasonably conclusive.

**Comment by pkgdemon** [comment] 2016-12-31 21:35
Closing for now due to lack of required information to reproduce.

**Comment by grahamperrin** [comment] 2017-01-01 08:16
> Results from today's test with the MacBookPro5,2, which does not require an extension cable, seem reasonably conclusive.

MacBookPro5,2 + D-Link DWL-G122 rev C1 + encrypted TrueOS Desktop booting from a USB flash drive **without** `savecache` service at runlevel `shutdown`:

- very many successes, enough for me to treat `savecache` as an offending service. 

This morning I **reintroduced the offending service** to that USB flash drive and as I expected: 

- **all** subsequent boots (at least five, the last three of which were with, without then with [atp](https://www.freebsd.org/cgi/man.cgi?query=atp&sektion=4&manpath=FreeBSD)(4)) **failed to gain the wlan0 interface** for the D-Link. 

I shutdown the MacBookPro5,2, removed both USB devices and introduced them – and the offending service – to a different computer …

----

HP EliteBook 8540p with the USB flash drive in its left port, D-Link in the rearmost of its right ports: 

- EFI blind mode and I did not get (or did not wait long enough for) the display manager, so I pressed the ACPI power button to shut down the OS. 

On to a different computer … 

---- 

Ergo Vista 621 with the USB flash drive in a port at the rear (the left, viewed from the front), D-link in the rearmost of its right ports: 

- the flash drive was not found so I retried with a swap of positions (flash drive in the rearmost of its right ports) but still it was not found so I pressed the ACPI power button to stop the computer. 

On to a different computer … 

----

MacBookPro11,2 with the USB flash drive to the left, D-Link to the right: 

- **failed to gain the wlan0 interface** for the D-Link. 

So I **deleted the offending service**, restarted the OS: 

- success; there's `wlan0`, associated with my preferred network and good for Internet service.

**Comment by pkgdemon** [comment] 2017-01-02 16:32
Can you provide the output of kldstat before, and after the problem?

**Comment by grahamperrin** [comment] 2017-01-02 17:52
Before: 

```
$ date ; uptime ; uname -n
Mon  2 Jan 2017 17:51:00 GMT
 5:51p.m.  up  4:19, 5 users, load averages: 0.83, 0.87, 0.78
momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk
$ kldstat
Id Refs Address            Size     Name
 1  162 0xffffffff80200000 1e9c038  kernel
 2    1 0xffffffff8209e000 312468   zfs.ko
 3    2 0xffffffff823b1000 c808     opensolaris.ko
 4    1 0xffffffff823be000 21b50    geom_eli.ko
 5    1 0xffffffff823e0000 12c48    tmpfs.ko
 6    1 0xffffffff823f3000 b590     aesni.ko
 7    1 0xffffffff82911000 3ecc6    linux.ko
 8    4 0xffffffff82950000 7830     linux_common.ko
 9    1 0xffffffff82958000 3a90f    linux64.ko
10    2 0xffffffff82993000 4265     libiconv.ko
11    1 0xffffffff82998000 2441     libmchain.ko
12    1 0xffffffff8299b000 786      msdosfs_iconv.ko
13    1 0xffffffff8299c000 371c2    if_bwn.ko
14    1 0xffffffff829d4000 82af     siba_bwn.ko
15    1 0xffffffff829dd000 1fdb2    if_bwi.ko
16    1 0xffffffff829fd000 26e5     runfw.ko
17    1 0xffffffff82a00000 1a0c9    if_iwm.ko
18    1 0xffffffff82a1b000 1209b7   iwm7265fw.ko
19    1 0xffffffff82b3c000 83a1     cuse.ko
20    1 0xffffffff82b45000 6db3     sem.ko
21    1 0xffffffff82b4c000 8d3d     geom_uzip.ko
22    1 0xffffffff82b55000 5887     fdescfs.ko
23    4 0xffffffff82b5b000 316c1    linuxkpi.ko
24    1 0xffffffff82b8d000 2e538    iwn4965fw.ko
25    1 0xffffffff82bbc000 52d5d    iwn1000fw.ko
26    1 0xffffffff82c0f000 539cc    iwn5000fw.ko
27    1 0xffffffff82c63000 52cec    iwn5150fw.ko
28    1 0xffffffff82cb6000 6f6c4    iwn6000fw.ko
29    1 0xffffffff82d26000 a5cad    iwn6000g2afw.ko
30    1 0xffffffff82dcc000 a6509    iwn6000g2bfw.ko
31    1 0xffffffff82e73000 7320d    iwn6050fw.ko
32    1 0xffffffff82ee7000 3667     acpi_video.ko
33    1 0xffffffff82eeb000 de62     fuse.ko
34    1 0xffffffff82ef9000 3bd0     ums.ko
35    1 0xffffffff82efd000 12c540   i915kms.ko
36    1 0xffffffff8302a000 81595    drm.ko
37    2 0xffffffff830ac000 5c0e     debugfs.ko
38    1 0xffffffff830b2000 a5a67    nvidia-modeset.ko
39    1 0xffffffff83158000 a13d0a   nvidia.ko
40    3 0xffffffff83b6c000 502e2    vboxdrv.ko
41    1 0xffffffff83bbd000 bdd3     linprocfs.ko
42    1 0xffffffff83bc9000 23cef    ipfw.ko
43    1 0xffffffff83bed000 1023d    if_rum.ko
44    1 0xffffffff83bfe000 8177     autofs.ko
45    2 0xffffffff83c07000 2ad6     vboxnetflt.ko
46    4 0xffffffff83c0a000 c69d     netgraph.ko
47    1 0xffffffff83c17000 42b0     ng_ether.ko
48    1 0xffffffff83c1c000 3f9c     vboxnetadp.ko
49    1 0xffffffff83c20000 2959     uhid.ko
50    1 0xffffffff83c23000 4f25     ng_ubt.ko
51    1 0xffffffff83c28000 a577     ng_hci.ko
52    1 0xffffffff83c33000 105c     ng_bluetooth.ko
$ 
```

(I'll edit this comment to include the _after_. Expecting loss of connectivity.)

**Comment by grahamperrin** [comment] 2017-01-02 18:14
After (again, fifty-two entries, I performed a diff, the fifty-two are equal): 

```
$ date ; uptime ; uname -v
Mon  2 Jan 2017 17:57:52 GMT
 5:57p.m.  up  4:26, 2 users, load averages: 0.44, 0.71, 0.75
FreeBSD 12.0-CURRENT #12 5ef9376(drm-next-4.7): Thu Dec 29 16:26:36 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys/GENERIC 
$ kldstat
Id Refs Address            Size     Name
 1  162 0xffffffff80200000 1e9c038  kernel
 2    1 0xffffffff8209e000 312468   zfs.ko
 3    2 0xffffffff823b1000 c808     opensolaris.ko
 4    1 0xffffffff823be000 21b50    geom_eli.ko
 5    1 0xffffffff823e0000 12c48    tmpfs.ko
 6    1 0xffffffff823f3000 b590     aesni.ko
 7    1 0xffffffff82911000 3ecc6    linux.ko
 8    4 0xffffffff82950000 7830     linux_common.ko
 9    1 0xffffffff82958000 3a90f    linux64.ko
10    2 0xffffffff82993000 4265     libiconv.ko
11    1 0xffffffff82998000 2441     libmchain.ko
12    1 0xffffffff8299b000 786      msdosfs_iconv.ko
13    1 0xffffffff8299c000 371c2    if_bwn.ko
14    1 0xffffffff829d4000 82af     siba_bwn.ko
15    1 0xffffffff829dd000 1fdb2    if_bwi.ko
16    1 0xffffffff829fd000 26e5     runfw.ko
17    1 0xffffffff82a00000 1a0c9    if_iwm.ko
18    1 0xffffffff82a1b000 1209b7   iwm7265fw.ko
19    1 0xffffffff82b3c000 83a1     cuse.ko
20    1 0xffffffff82b45000 6db3     sem.ko
21    1 0xffffffff82b4c000 8d3d     geom_uzip.ko
22    1 0xffffffff82b55000 5887     fdescfs.ko
23    4 0xffffffff82b5b000 316c1    linuxkpi.ko
24    1 0xffffffff82b8d000 2e538    iwn4965fw.ko
25    1 0xffffffff82bbc000 52d5d    iwn1000fw.ko
26    1 0xffffffff82c0f000 539cc    iwn5000fw.ko
27    1 0xffffffff82c63000 52cec    iwn5150fw.ko
28    1 0xffffffff82cb6000 6f6c4    iwn6000fw.ko
29    1 0xffffffff82d26000 a5cad    iwn6000g2afw.ko
30    1 0xffffffff82dcc000 a6509    iwn6000g2bfw.ko
31    1 0xffffffff82e73000 7320d    iwn6050fw.ko
32    1 0xffffffff82ee7000 3667     acpi_video.ko
33    1 0xffffffff82eeb000 de62     fuse.ko
34    1 0xffffffff82ef9000 3bd0     ums.ko
35    1 0xffffffff82efd000 12c540   i915kms.ko
36    1 0xffffffff8302a000 81595    drm.ko
37    2 0xffffffff830ac000 5c0e     debugfs.ko
38    1 0xffffffff830b2000 a5a67    nvidia-modeset.ko
39    1 0xffffffff83158000 a13d0a   nvidia.ko
40    3 0xffffffff83b6c000 502e2    vboxdrv.ko
41    1 0xffffffff83bbd000 bdd3     linprocfs.ko
42    1 0xffffffff83bc9000 23cef    ipfw.ko
43    1 0xffffffff83bed000 1023d    if_rum.ko
44    1 0xffffffff83bfe000 8177     autofs.ko
45    2 0xffffffff83c07000 2ad6     vboxnetflt.ko
46    4 0xffffffff83c0a000 c69d     netgraph.ko
47    1 0xffffffff83c17000 42b0     ng_ether.ko
48    1 0xffffffff83c1c000 3f9c     vboxnetadp.ko
49    1 0xffffffff83c20000 2959     uhid.ko
50    1 0xffffffff83c23000 4f25     ng_ubt.ko
51    1 0xffffffff83c28000 a577     ng_hci.ko
52    1 0xffffffff83c33000 105c     ng_bluetooth.ko
$ ifconfig wlan0
ifconfig: interface wlan0 does not exist
$ 
```

**Comment by grahamperrin** [comment] 2017-01-02 20:59
Issue and workaround reproduced with the D-Link device connected to a [Samsung NF110](http://www.samsung.com/uk/support/model/NP-NF110-A01UK) netbook.

**Comment by pkgdemon** [comment] 2017-01-02 22:08
Looks like that is kldstat before?  What does kldstat look like after?

**Comment by grahamperrin** [comment] 2017-01-03 07:41
Truly, those were the before and after. 

Before the problem, _without_ the service: 

```
Mon  2 Jan 2017 18:29:02 GMT
 6:29p.m.  up 1 min, 1 users, load averages: 1.66, 0.58, 0.22
```

Still before the problem: 

```
$ sudo rc-update add savecache shutdown
Password:
 * service savecache added to runlevel shutdown
$ 
```

Then the restart (… run of `savecache` … start). 

After that restart, with the problem: 

```
Mon  2 Jan 2017 18:33:39 GMT
 6:33p.m.  up 2 mins, 1 users, load averages: 1.52, 0.55, 0.21
```

**Comment by grahamperrin** [comment] 2017-01-13 17:57
https://discourse.trueos.org/t/trueos-desktop-2016-12-27-x64-and-ipv4-lan-with-dhcp/595/11: 

> … With TrueOS from 10/28/2016, wlan (D-Link, USB) worked "out of the box". But every update since then killed it.
> 
> I decided to do a fresh install with 12/27/2016 (the latest). Result: no wlan. …

**Comment by grahamperrin** [comment] 2017-01-13 23:34
From https://gitter.im/trueos/Random?at=587959a4dec171b811e7d9b3: 

> … Thank you ! 

> … after reboot rc-update delete savecache shutdown.png

![after-reboot-rc-update-delete-savecache-shutdown](https://cloud.githubusercontent.com/assets/192271/21949281/c399287a-d9e8-11e6-9fa4-bed871ade5a3.png)

From https://gitter.im/trueos/troubleshooting?at=587962c611e7a7f61d935f1c: 

> `wlans_urtw0="wlan0"`

**Comment by pkgdemon** [comment] 2017-01-17 22:09
I encountered this with another user with built in wireless at the office using ```if_run```.  Adding the kernel module to modules fixes.  The issue seems to be devd starting after networking and loading the kernel module after network.  In your case you could try adding ```if_rum``` to /etc/conf.d/modules to see if that resolves it without the removal of savecache as well.

**Comment by grahamperrin** [comment] 2017-01-18 18:43
Thanks. [rum](https://www.freebsd.org/cgi/man.cgi?query=rum&sektion=4&manpath=FreeBSD)(4) tests progressing at a MacBookPro11,2 

For the @Mystified1234 case, [urtw](https://www.freebsd.org/cgi/man.cgi?query=urtw&sektion=4&manpath=FreeBSD)(4) and I guess that `/etc/conf.d/modules` should include `if_urtw`

**Comment by grahamperrin** [comment] 2017-01-18 19:37
**Tested successfully** at the MacBookPro11,2: 

- restarts
- power on after ACPI shutdown

– with both `atp` and `if_rum` in `/etc/conf.d/modules`

**Comment by pkgdemon** [comment] 2017-01-18 19:41
Yeah.  For now I am going to add these into our stock modules file.  It is what we have always done in PC-BSD anyway.  When we have devd working properly I can revert.

**Comment by pkgdemon** [comment] 2017-01-18 20:17
Fixed will be in next unstable push after packages build.  https://github.com/trueos/trueos-core/commit/d0da1659cbaf9b940f77b3932ef299fb74189d23

**Comment by grahamperrin** [comment] 2017-01-19 00:52
Should we also add `urtw` for the case at https://github.com/trueos/trueos-core/issues/252#issuecomment-272576638 above? 

(Maybe overlooked, the light grey of the quoted text.)

**Comment by pkgdemon** [comment] 2017-01-19 23:09
Ah.  I overlooked this or may have mixed the tickets up.  Will reopen until i get it added, and pushed.

**Comment by pkgdemon** [comment] 2017-01-20 18:26
https://github.com/trueos/trueos-core/commit/491b7e6879af15a26e8eff659595e0915af2d70c

**Closed by pkgdemon** 2017-01-20 18:26 UTC
Labels: info:feedback_needed
