### ISSUE TITLE
"Off by 8 error" in network streams under TrueOS-Desktop-201702011813 (UNSTABLE) and later

### ISSUE THREAD

**Issue by baitisj** [trueos/trueos-core#327] opened 2017-02-12 19:45 UTC
After upgrade, I witnessed broken images and incorrectly loaded web pages. `git pull` resulted in:

```text
Fssh_ssh_dispatch_run_fatal: Connection to XXX: message authentication code incorrect
```

Reverting to a previous BE from January 24 solved the problem.

```text
$ uname -a
FreeBSD raid.baitis.home 12.0-CURRENT FreeBSD 12.0-CURRENT #18 4f888bf(drm-next): Wed Jan 18 14:31:26 UTC 2017     root@gauntlet:/usr/obj/usr/src/sys/GENERIC  amd64
```

```text
$ about -v
General info:
       Host:...............raid.baitis.home
       User:...............baitisj
       Uptime:.............48 mins
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....27d3221
       TrueOS ver:.........TrueOS-Desktop-201702011813
       Arch:...............amd64
       Kernel ident:.......GENERIC
       Bootloader:.........BSD
       Bootloader type:....BIOS
       CPU:................Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
       CPU cores:..........4
       Memory (free/avail):27955 / 33248 Mb
       Package set:........UNSTABLE
       Desktop environment:Xfce Session
       X11 Driver:.........nvidia_drv.so nv_drv.so vesa_drv.so 
       OSS Driver:.........pcm3: <Realtek (0x0280) (Rear Analog)> (play/rec) default
       WIFI Driver:........

Network IPV4 address: 
       192.168.8.2
       127.0.0.1

Network IPv6 address: 
       donot::findme:ohno:sece:tinf%em0
       ::1
       fe80::1%lo0
```

Hardware:
```text
$ lspci -v
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v3 Processor DRAM Controller (rev 06)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor PCI Express x16 Controller (rev 06)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:16.3 Serial controller: Intel Corporation 8 Series/C220 Series Chipset Family KT Controller (rev 04)
00:19.0 Ethernet controller: Intel Corporation Ethernet Connection I217-LM (rev 04)
00:1a.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d4)
00:1c.1 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #2 (rev d4)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d4)
00:1d.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB EHCI #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation C226 Series Chipset Family Server Advanced SKU LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 8 Series/C220 Series Chipset Family 6-port SATA Controller 1 [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GK208 [GeForce GT 730] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK208 HDMI/DP Audio Controller (rev a1)
03:00.0 PCI bridge: Texas Instruments XIO2001 PCI Express-to-PCI Bridge
05:00.0 SATA controller: ASMedia Technology Inc. ASM1062 Serial ATA Controller (rev 01)
```

**Comment by pkgdemon** [comment] 2017-02-13 04:14
After looking up the ```Fssh_ssh_dispatch_run_fatal: Connection to XXX: message authentication code incorrect``` error it sounds like you are using some kind of ssh tunnel?  Is this with the built in OpenSSH, or OpenSSH from ports?

**Comment by baitisj** [comment] 2017-02-14 06:25
I am assuming that `git` is creating a SSH tunnel.
This was 100% from `pkg upgrade -f` / TrueOS automatic updater

**Comment by baitisj** [comment] 2017-02-20 07:12
I updated to the latest UNSTABLE build, and am still receiving intermittent MAC errors, broken page loads, and failed checksum errors when downloading packages from the repository; e.g.:
```text
$ sudo pkg install wireshart
Password:
Updating trueos-base repository catalogue...
trueos-base repository is up-to-date.
Updating trueos-major repository catalogue...
trueos-major repository is up-to-date.
All repositories are up-to-date.
pkg-static: No packages available to install matching 'wireshart' have been found in the repositories
(ins)baitisj@raid: /usr/ports/ $ sudo pkg install wireshark
Updating trueos-base repository catalogue...
trueos-base repository is up-to-date.
Updating trueos-major repository catalogue...
trueos-major repository is up-to-date.
All repositories are up-to-date.
The following 4 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	wireshark: 2.2.4 [trueos-major]
	libyaml: 0.1.6_2 [trueos-major]
	libsmi: 0.4.8_1 [trueos-major]
	GeoIP: 1.6.9 [trueos-major]

Number of packages to be installed: 4

The process will require 100 MiB more space.
16 MiB to be downloaded.

Proceed with this action? [y/N]: y
Fetching wireshark-2.2.4.txz: 100%   14 MiB   1.2MB/s    00:12    
pkg-static: wireshark-2.2.4 failed checksum from repository
```
Some selected information
```
$ about -v
       FreeBSD kernel ver:.12.0-CURRENT
       FreeBSD world ver:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....f1f0286
       TrueOS ver:.........TrueOS-Desktop-201702152315
```

**Comment by pkgdemon** [comment] 2017-02-20 18:04
What do the mac errors say?

**Comment by baitisj** [comment] 2017-02-20 21:55
In short, I'm not sure what you're asking, or where to begin.

The MAC errors appear to be detected whenever SSL or another cryptographic layer is involved in verifying the network data. In the case of the aforementioned wireshark package, my guess is that `pkg` is performing a `sha256` and comparing the result on the downloaded file with some sort of master file, and the sums are not matching.

I'll do some more extensive tests involving `curl` and `wireshark` to try to figure out where the problem lies. My guess? Data captured by the ethernet adapter is either 1. being corrupted or 2. buffers are not being mapped into memory correctly and are getting truncated, but this is highly speculative.

**Comment by pkgdemon** [comment] 2017-02-21 03:26
Maybe this is a libressl 4.4.6 regression?  I think @kmoore134 is working on bringing in 2.5.1 before the next unstable.  Im just not sure what MAC error means.  I was assuming that was an error you saw in a log?  Or is that just a term to describe the systems you are seeing?

**Comment by baitisj** [comment] 2017-02-21 03:42
If you look at the second line of the first comment I made about this problem, it states:
```text
Fssh_ssh_dispatch_run_fatal: Connection to XXX: message authentication code incorrect
```
Hence, MAC (message authentication code) error

I can only assume the same error is being seen in other SSL-related stuff.

**Comment by baitisj** [comment] 2017-02-21 03:43
Oh, look here. This is very telling:

**Comment by baitisj** [comment] 2017-02-21 03:45
My system has libressl-2.4.5 installed. I'm going to rebuild from ports and see if that fixes things.

**Comment by baitisj** [comment] 2017-02-21 03:57
This issue is **not** limited to SSL connections. Here is my latest test:
```text
$ curl http://norvig.com/big.txt -o big.txt
$ curl curl http://norvig.com/big.txt -o big2.txt
$ sha256 big.txt 
SHA256 (big.txt) = a36fe438864ad8c7b76ca310c2d1176689bbf79536f84338ebd3dc253997efd5
$ sha256 big2.txt 
SHA256 (big2.txt) = 71f0fa4bf8585feae457dbfc0b48dd6dfef8dcd03a07220a5754e0876b9e4efc
```

**Comment by baitisj** [comment] 2017-02-21 03:57
This issue is **not** limited to SSL connections. Here is my latest test:
```text
$ curl http://norvig.com/big.txt -o big.txt
$ curl curl http://norvig.com/big.txt -o big2.txt
$ sha256 big.txt 
SHA256 (big.txt) = a36fe438864ad8c7b76ca310c2d1176689bbf79536f84338ebd3dc253997efd5
$ sha256 big2.txt 
SHA256 (big2.txt) = 71f0fa4bf8585feae457dbfc0b48dd6dfef8dcd03a07220a5754e0876b9e4efc
```

**Comment by baitisj** [comment] 2017-02-21 03:59
Here's the very interesting and telling output from
```text
diff -u big.txt big2.txt
```
[diff.txt](https://github.com/trueos/trueos-core/files/789035/diff.txt)

**Comment by baitisj** [comment] 2017-02-21 04:10
After analyzing the diff posted above, the corruption occurs resulting in an **off by 8** value injected in the data stream. For example, if you look at the first pairs of characters that are different (code in `python3`):

```
+>>> ord('m') - ord('e')
8
+>>> ord('m') - ord('e')
8
+>>> ord(' ') - ord('(')
-8
+>>> ord('a') - ord('i')
-8
```

**Comment by baitisj** [comment] 2017-02-21 04:35
I downloaded the textfile three more times and did an analysis, and the interval (offset) at which the corruption takes place seems to be random, but it is very consistently off by 8

**Comment by baitisj** [comment] 2017-02-21 04:48
Kernel module:
[if_em.zip](https://github.com/trueos/trueos-core/files/789091/if_em.zip)

```text
$ ifconfig -a
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=53d9b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,LRO,WOL_UCAST,WOL_MCAST,WOL_MAGIC,VLAN_HWFILTER,VLAN_HWTSO>
	ether de:ad:be:0e:0e:ef
	inet6 donot::findme:ohno:sece:tinf%em0 prefixlen 64 scopeid 0x1 
	inet 192.168.8.2 netmask 0xffffff00 broadcast 192.168.8.255 
	nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
```

**Comment by pkgdemon** [comment] 2017-02-21 12:16
Could this be related?  https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=210901

**Comment by baitisj** [comment] 2017-02-21 16:40
I don't think this is related especially as what I am experiencing is a new issue as of Jan 24 or so
the corruption doesn't occur under heavy load. it occurs under every load

I have verified the following `sysctl` values are set:

```text
hw.em.txd: 1024
hw.em.rxd: 1024
hw.em.rx_process_limit: 100
```

I will attempt to 
```text
git clone https://www.github.com/freebsd/freebsd.git --depth=1 /usr/src
cd /usr/src
make buildkernel
```
and attempt to determine if symptoms persist.

**Comment by baitisj** [comment] 2017-02-22 00:40
I have verified that this problem exists upstream.

```file
$ uname -a
FreeBSD raid.baitis.home 12.0-CURRENT FreeBSD 12.0-CURRENT #1 7a0e1ff53(master)-dirty: Tue Feb 21 15:07:06 PST 2017     baitisj@raid.baitis.home:/usr/obj/usr/src/sys/GENERIC  amd64
$ cd /usr/src/
$ git log
commit 7a0e1ff531c8c910508f2b6980ec0565bb7884b6
Author: trasz <trasz@FreeBSD.org>
Date:   Tue Feb 21 15:57:01 2017 +0000

    Get rid of foo_sys() in linuxulator code.  It was commented out, and it
    would be useless anyway - there is no point in pretending to have block
    devices; our "block" devices are in fact character ones, and can only
    be accessed as such.
...
```

**Comment by baitisj** [comment] 2017-02-22 05:44
Reported upstream at: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=217287

**Comment by pkgdemon** [comment] 2017-02-22 17:12
Thanks @baitisj.  I will watch the upstream ticket for activity.  You might also want to send something to the freebsd-current mailing list.  Closing this ticket for now since there is nothing further we can do on our end.

**Closed by pkgdemon** 2017-02-22 17:12 UTC
Labels: priority:high

**Comment by baitisj** [comment] 2017-04-30 14:34
For tracking purposes, the issue is still present in:
```
===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20170430_065121 NR 2017-04-30
       after restart (R) … 12.0-CURRENT-up-20170430_065121 NR 2017-04-30
boot loader …………………………………… BSD
            type ……………………… BIOS
CPU ………………………………………………………… Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
    number of cores ……………… 4
host ……………………………………………………… raid.baitis.home
memory ………………………………………………… 33248 MB available, 29950 MB free
OS git branch ……………………………………………………………………………………… drm-next
OS git revision ………………………………………………………………………………… 96a971c9a
OS kernel build time ………………………………………………………… Mon 2017 Apr 17 18:50:02 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… UNSTABLE
TrueOS version …………………………… TrueOS-Desktop-201704211306
uptime ………………………………………………… 6 mins
user  …………………………………………………… baitisj

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm3: <Realtek (0x0280) (Rear Analog)> (play/rec) default
    wireless driver ……………… 
    X11 drivers ………………………… nvidia_drv.so 
```

**Comment by baitisj** [comment] 2017-07-26 04:58
For those concerned, this bug is still present in the kernel in TrueOS-2017-07-14-x64.
