### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#181] opened 2016-12-03 06:20 UTC
Hi All,

Trying to `go get` a project but failing because of a certificate issue.
Here it is failing with curl:

```
% curl https://go.googlesource.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

This same curl command works on a freebsd 11-release machine and I copied over cert.pem.

Any clues?

**Comment by pkgdemon** [comment] 2016-12-05 18:34
Seeing this here also.  Not sure what the issue is yet.

**Comment by jungle-boogie** [comment] 2016-12-05 18:50
@pkgdemon, My first guess was something dealing with curl linking to libressl.

```
/usr/local/bin/curl:
        libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x80084b000)
        libz.so.6 => /lib/libz.so.6 (0x800ab2000)
        libthr.so.3 => /lib/libthr.so.3 (0x800cc9000)
        libc.so.7 => /lib/libc.so.7 (0x800ef0000)
        libssl.so.39 => /usr/local/lib/libssl.so.39 (0x8012aa000)
        libcrypto.so.38 => /usr/local/lib/libcrypto.so.38 (0x801505000)
```


Actually, I'm seeing issues with just curl to google!

```
% curl https://www.google.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by jungle-boogie** [comment] 2016-12-08 18:58
Any suggestions on how I can help find the cause?

**Comment by kmoore134** [comment] 2016-12-08 19:11
I assume you have the nss bundle installed? #pkg info ca_root_nss

Also, looks like its incorrectly linked to ports version of libressl? We have that in base system now. When you run 'pkg delete libressl' does it complain about needing to remove a ton of other things?

**Comment by jungle-boogie** [comment] 2016-12-08 20:00
yes to both.

```
% pkg info ca_root_nss
ca_root_nss-3.27.1
Name           : ca_root_nss
Version        : 3.27.1
Installed on   : Tue Nov 29 22:50:44 2016 PST
Origin         : security/ca_root_nss
Architecture   : freebsd:12:*
Prefix         : /usr/local
Categories     : security
Licenses       : MPL
Maintainer     : ports-secteam@FreeBSD.org
WWW            : UNKNOWN
Comment        : Root certificate bundle from the Mozilla Project
Options        :
        ETCSYMLINK     : on
Annotations    :
Flat size      : 896KiB
Description    :
Root certificates from certificate authorities included in the Mozilla
NSS library and thus in Firefox and Thunderbird.

This port directly tracks the version of NSS in the security/nss port.
```

```
Number of packages to be removed: 196
The operation will free 3 GiB.
```

**Comment by jungle-boogie** [comment] 2016-12-08 20:01
and for go:
```
% ldd /usr/local/bin/go
/usr/local/bin/go:
        libthr.so.3 => /lib/libthr.so.3 (0x800c27000)
        libc.so.7 => /lib/libc.so.7 (0x800e4e000)
```

**Comment by pkgdemon** [comment] 2016-12-10 22:11
![google cert](https://cloud.githubusercontent.com/assets/4109732/21076520/9b64d550-befb-11e6-8054-d1cbeb6104d8.png)

**Comment by pkgdemon** [comment] 2016-12-10 22:15
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=213210

**Comment by pkgdemon** [comment] 2016-12-10 22:31
https://www.bountysource.com/issues/11443345-libressl-fails-to-verify-alternate-chains

**Comment by jungle-boogie** [comment] 2016-12-11 01:20
Building libressl-portable from source (from 2.4.2 to 2.5.1), allows the connection to google and go.googlesource.com to work as expected.

**Comment by pkgdemon** [comment] 2016-12-11 01:31
Cool.  That's what I was expecting based on the conversations in the links above.   Glad to have confirmation a new version will fix.

**Comment by pkgdemon** [comment] 2017-01-01 00:42
Closing for now.  This depends on 2.4.5 to fix which doesn't appear to be coming any time soon.

**Comment by sean-** [comment] 2017-02-19 07:01
Definitely looking forward to seeing the base version bumped to libressl `2.5.1`.  For those that stumble across this issue, there is a work around:

```
sudo pkg delete -f libressl
sudo pkg install libressl-devel
sudo mkdir /lib/libressl-245 /usr/lib/libressl-245
sudo cp -p /lib/libcrypto* /lib/libressl-245/
sudo cp -p /usr/lib/lib{crypto,ssl}.* /usr/lib/libressl-245/
sudo cp -p /usr/local/lib/libssl* /usr/lib/
sudo cp -p /usr/lib/libssl.so.{43,38}
sudo cp -p /lib/libcrypto.so.{41,38}
```

Far from recommended, but it works and gets people out of a jam who are using `go get` (which calls `git`) and are unable to fetch dependencies that traverse through https://go.googlesource.com

**Comment by howdoicomputer** [comment] 2017-02-19 10:20
@sean- Hm, that doesnt seem to work for me.

**Comment by pkgdemon** [comment] 2017-02-19 16:10
Thanks @sean-.  I will test the workaround as well, and also bring this to Barnerd's attention.  This sounds like more than just a versioning bump issue.

**Comment by sean-** [comment] 2017-02-19 21:34
@howdoicomputer I think I missed a `cp` in `/usr/local/lib` for the work around.  Can you see if there's an old version of `libssl*` in `/usr/local/lib` that also needs to be clobbered?

@pkgdemon please.  TrueOS is basically useless atm when using Go *if* you need to pull down sources from Google.

**Comment by howdoicomputer** [comment] 2017-02-19 23:07
@sean- I, uh, no longer have TrueOS on my system; went back to Linux for some Golang and Netflix goodness.

I'm still kind of interested in BSD so I may set up a small partition for playing around with it. Also, it looks like uninstalling the libressl package would be a *very* short term fix as a lot of other packages depend on it so it ends up being reinstalled.

**Comment by sean-** [comment] 2017-02-19 23:14
Doh! I kept libressl installed but clobbered with a -f install to keep the same package dependencies present. There used to be a `-O` flag that would let you upgrade and update the origin... it may exist but is now lost behind a flag and some rando flag in the package database. pkgNG has its perks and warts. :-/

**Comment by kmoore134** [comment] 2017-02-20 00:41
I'll take a crack at getting LibreSSL 2.5.1 into our base soon, unless Barnerd beats me to it :)

**Comment by pkgdemon** [comment] 2017-02-22 13:17
Go get is working for me on latest unstable.  Still having issues with curl.

**Closed** 2017-02-22 14:24 UTC
Labels: status:3rd_party_to_resolve
