### ISSUE TITLE
default route lost

### ISSUE THREAD

**Issue by jungle-boogie** [trueos/trueos-core#174] opened 2016-11-28 15:36 UTC
Hi All,

I have observed after rebooting my computer and having it connected to a wifi connection for 30 minutes, I cannot access anything outside my LAN, but I can still ping the default gateway and devices on the LAN. Pinging sites via domain or IP address result in the same message:
`ping: sendto: No route to host`

Once this starts and I'm not able to connect to websites, I `sudo killall dhcpcd` and then `sudo /usr/local/sbin/dhcpcd`, which will give me a good working connection for the duration of my laptop being powered on.

I'm stating 30 minutes because I did the following:

0. rebooted the laptop
1. logged in
2. setup a ping to yahoo.com once a minute and write to a file
3. observed how many pings were in the file

```
% pciconf -lv ath0
ath0@pci0:3:0:0:	class=0x028000 card=0x662711ad chip=0x0032168c rev=0x01 hdr=0x00
    vendor     = 'Qualcomm Atheros'
    device     = 'AR9485 Wireless Network Adapter'
    class      = network
```

```
% dmesg | grep ath0
ath0: <Atheros AR9485> mem 0xb2000000-0xb207ffff irq 19 at device 0.0 on pci3
ath0: [HT] enabling HT modes
ath0: [HT] enabling short-GI in 20MHz mode
ath0: [HT] 1 stream STBC receive enabled
ath0: [HT] 1 RX streams; 1 TX streams
ath0: AR9485 mac 576.1 RF5110 phy 1638.6
ath0: 2GHz radio: 0x0000; 5GHz radio: 0x0000
ath0: <Atheros AR9485> mem 0xb2000000-0xb207ffff irq 19 at device 0.0 on pci3
ath0: [HT] enabling HT modes
ath0: [HT] enabling short-GI in 20MHz mode
ath0: [HT] 1 stream STBC receive enabled
ath0: [HT] 1 RX streams; 1 TX streams
ath0: AR9485 mac 576.1 RF5110 phy 1638.6
ath0: 2GHz radio: 0x0000; 5GHz radio: 0x0000
```

I have not tried:
wired connection
different wireless dongle

Anything I can provide to assist with discovering the root cause?

`12.0-CURRENT FreeBSD 12.0-CURRENT #40 a8b0e29(drm-next-4.7): Tue Nov 22 16:43:26 UTC 2016     root@gauntlet:/usr/obj/usr/src/sys`

**Comment by kmoore134** [comment] 2016-11-28 16:52
Looks like the known issue we are seeing with dhcpcd renewing leases. Joe is investigating

**Comment by jungle-boogie** [comment] 2016-11-28 17:13
hi @kmoore134, is there a issue # on it that I can track?

**Comment by jungle-boogie** [comment] 2016-11-28 17:32
I see he cloned the repo:
https://github.com/trueos/dhcpcd

**Comment by pkgdemon** [comment] 2016-11-29 00:39
@jungle-boogie This is the ticket to track.  After a discussion with the author of dhcpcd I pulled in a early release of dhcpcd which is supposed to fix this issue into a git repo.  I may, or may not roll a port from it depending on what this does so that the next set of packages can fix.  

However after further investigation DHCP was listening on all interfaces rather than just defined interfaces.  

Can you try fetching this updated script to /usr/local/etc/init.d/dhcpcd?  

https://raw.githubusercontent.com/trueos/freebsd-ports/828dfd2591948594825a1964cee680220f439174/net/dhcpcd/files/dhcpcd.in

When you copy it without the .in extension make sure to mark it executable with chmod +x, and reboot.

I added an interfaces line to only enabled DHCP on specific interfaces.  Rather than any interface which is what is was doing by default.

**Comment by pkgdemon** [comment] 2016-11-29 00:49
I will be testing this as well.  Just waiting for my lease to expire which I could only to an hour at the moment.  :)

**Comment by jungle-boogie** [comment] 2016-11-29 00:58
hi @pkgdemon,

Thanks for taking a look at this issue.

Just curious, who is the author of dhcpcd. Is it Bapt? Surprised to see fossil in use and I know he does a lot with fossil.

I'll fetch the file and see what happens after half an hour or so!

**Comment by pkgdemon** [comment] 2016-11-29 01:26
@jungle-boogie Roy Marples is the author.

http://roy.marples.name/projects/dhcpcd/index

**Comment by pkgdemon** [comment] 2016-11-29 01:52
@jungle-boogie I see this now after lowering my lease times.  I lost my default route after half that time.  Are you able to ping your router when you lose connectivity but not able to ping outside such as to 8.8.8.8?

**Comment by jungle-boogie** [comment] 2016-11-29 03:16
> To get connected again. When you lose connectivity are you able to ping your router but not able to ping an outside address such as to 8.8.8.8 (google)?

yes, I can ping and reach anything on the LAN but nothing external. Your trick of adding the route back is a good idea. I've been killing dhcpcd and starting it back up because I didn't know what to check.

**Comment by pkgdemon** [comment] 2016-11-29 03:43
I should have a port for v7 by tommorow.  I have been runnimg with it for over an hour, and it seems to fix the issue.  I am going to let it sit overnight to be sure.  Will ping when the port is ready.  We we rebuild packages, and push same day.

**Comment by jungle-boogie** [comment] 2016-11-29 03:50
Great job, @pkgdemon.

no route:
```
% netstat -r
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
localhost          link#2             UH          lo0
192.168.0.0/24     link#3             U         wlan0
192.168.0.11       link#3             UHS         lo0
```

after my hack of starting/stopping dhcpcd
```
% netstat -r
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            192.168.0.1        UGS       wlan0
localhost          link#2             UH          lo0
192.168.0.0/24     link#3             U         wlan0
192.168.0.11       link#3             UHS         lo0
```

**Comment by pkgdemon** [comment] 2016-11-30 01:09
I can confirm the update port is working.  We have a bit more work to do to ensure it doesn't run on interfaces when DHCP is not set on anything.  May be tomorow before we push it but you can clone the ports tree, and build it like so:

```git clone https://www.github.com/trueos/freebsd-ports --depth=1 /usr/ports/```
```cd /usr/ports/net/dhcpcd/```
```make```
```make deinstall```
```make reinstall```

**Comment by jungle-boogie** [comment] 2016-11-30 01:10
Thanks, @pkgdemon. I'll clone and see what it does for me, too!

**Comment by pkgdemon** [comment] 2016-11-30 01:44
@jungle-boogie No problem.  If you get any errors with make you may need to ```pkg install llvm38``` also.  I forgot that we do not bundle that anymore in base but it is required for ports.

**Comment by pkgdemon** [comment] 2016-12-02 00:51
Fixed in newest UNSTABLE packages.

**Closed by pkgdemon** 2016-12-02 00:51 UTC
