### ISSUE TITLE
iwm(4): existing wlan0 does not exist after a system tray icon is used to 'Restart the Network'

### ISSUE THREAD

**Issue by grahamperrin** [trueos/trueos-core#265] opened 2017-01-01 15:23 UTC
wlan0 disappeared, 
[2017-01-01 14-04 terminal output.txt](https://github.com/trueos/trueos-core/files/680046/2017-01-01.14-04.terminal.output.txt)
somehow I regained it (a restart of the OS, I guess), I logged in to Lumina, began recording the screen and reproduced the issue, 
[2017-01-01 14-40 terminal output.txt](https://github.com/trueos/trueos-core/files/680047/2017-01-01.14-40.terminal.output.txt)

## Environment

- [HP EliteBook 850 G2](https://discourse.trueos.org/t/hp-elitebook-850-g2/343?u=grahamperrin)
- Intel Core i7-5500U
- https://www.freebsd.org/cgi/man.cgi?query=iwm&sektion=4&manpath=FreeBSD

[pciconf -lv.txt](https://github.com/trueos/trueos-core/files/680048/pciconf.-lv.txt)

```
$ cat /etc/rc.conf
rc_verbose="YES"
rc_interactive="YES"
rc_depend_strict="YES"
rc_parallel="NO"
rc_crashed_start="YES"
rc_logger="YES"
rc_log_path="/var/log/rc.log"
zfs_enable="YES"
kldload_i915kms="i915kms"
kldload_vbox="vboxdrv"
dbus_enable="YES"
# https://github.com/trueos/freebsd/commit/0af2dbd9b11c7ac54baef4b3bcd762f85bd3a658
linux_enable="YES"
wlans_iwm0="wlan0"
# wlans_rum0="wlan0"
ifconfig_wlan0="WPA DHCP"
ifconfig_em0="DHCP"
defaultrouter="193.62.168.1"
hostname="momh167-gjp4-hpelitebook850g2-trueos.university.brighton.ac.uk"
sshd_enable="YES"
vboxnet_enable="YES"
kldload_nvidia="nvidia-modeset nvidia"
ifconfig_em0_ipv6="inet6 accept_rtadv"
$ 
```

----

Since the second production of the bug, I have not regained use of wlan0. I'll work on it.

**Comment by grahamperrin** [comment] 2017-01-01 15:30
> Since the second production of the bug, I have not regained use of wlan0. 

Some time whilst drafting the opening post I noticed that the Wi-Fi switch above the keyboard of the notebook was amber. I know to not trust such indicators but I chose to press the switch. There was no change; it remained amber and there was no wlan0. 

Much later I realised that the switch had changed from amber to pale blue, and wlan0 has reappeared: 

```
$ date ; ifconfig wlan0 | grep -v ether
Sun  1 Jan 2017 15:24:07 GMT
wlan0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        inet 192.168.1.7 netmask 0xffffff00 broadcast 192.168.1.255 
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: IEEE 802.11 Wireless Ethernet OFDM/54Mbps mode 11a
        status: associated
        ssid piano channel 36 (5180 MHz 11a) bssid 58:1f:28:74:07:a8
        regdomain FCC country US authmode WPA2/802.11i privacy ON
        deftxkey UNDEF TKIP 2:128-bit txpower 17 bmiss 10 mcastrate 6
        mgmtrate 6 scanvalid 60 wme roaming MANUAL
        groups: wlan 
$ 
```

Note, this is **with** a concurrent wired connection to em0, which I changed from static to DHCP probably after connecting the cable. 

----

I aim to make the essence of this issue – disappearance of wlan0 – reproducible once more …

**Comment by grahamperrin** [comment] 2017-01-02 19:28
Reproduced again, twice. Probably consistently reproducible. 

For the most recent incident I ran `kldstat` before and after losing wlan0. Fifty-two lines, identical before and after.

**Comment by pkgdemon** [comment] 2017-01-02 22:13
I cannot reproduce on the STABLE build.  I suspect this is limited to this unreleased internal unstable.

**Comment by pkgdemon** [comment] 2017-01-05 16:31
Fixed in https://github.com/trueos/pc-networkmanager/commit/db4c54ee33cb28762eae143e5e4438b5ab287400 but it won't make this weeks unstable / stable.  Next week.

**Comment by pkgdemon** [comment] 2017-01-19 00:16
Reopening due to finding out the problem exists again with the network service itself.

**Comment by grahamperrin** [comment] 2017-01-19 01:35
To clarify: we treat https://github.com/trueos/trueos-core/issues/287 (_… OpenRC restart of network service_ (without reference to a GUI)) as a parent of this GUI-oriented issue 265, yes?

**Comment by pkgdemon** [comment] 2017-01-19 23:10
That is fine.

**Closed** 2017-03-30 22:36 UTC
Labels: status:confirmed
