### ISSUE TITLE
non destructive upgrade with 9-20-2016 iso fails

### ISSUE THREAD

**Issue by kahjs2007** [trueos/trueos-core#66] opened 2016-09-24 17:47 UTC
Running: chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
Generating grub configuration file ...
Found theme: /boot/grub/themes/trueos/theme.txt
done
Installing GRUB to ada0
Running: chroot /mnt /root/beadm.install activate 12.0-CURRENT-201609241225
Activated successfully
Running: rm /mnt/root/beadm.install
Running: umount -f /mnt/dev
Running: cp /boot/zfs/zpool.cache /mnt/boot/zfs/
cp: /boot/zfs/zpool.cache: No such file or directory
EXITERROR: Error 1: cp /boot/zfs/zpool.cache /mnt/boot/zfs/
Unmounting: /mnt
Running: umount -f /mnt

Full log attached as a txt file

[pc-sysinstall.log.txt](https://github.com/trueos/trueos-core/files/491256/pc-sysinstall.log.txt)

**Comment by grahamperrin** [comment] 2016-09-27 03:16
Maybe related: https://github.com/trueos/pc-sysinstall/issues/14

**Comment by kmoore134** [comment] 2016-09-27 13:09
Yep, it was a duplicate of trueos/pc-sysinstall#14

**Closed by kmoore134** 2016-09-27 13:09 UTC
Labels: duplicate
