### ISSUE TITLE
SysAdm: Control Panel -> Task Manager (desktop crash)

### ISSUE THREAD

**Issue by Unitrunker** [trueos/trueos-core#323] opened 2017-02-06 02:48 UTC
I see a consistent crash when selecting the Task Manager. I can see the task manager window for about a second before it dies.

fatal trap 9: general protection fault while in kernel mode
cpuid = 1, apic id = 01
instruction pointer = 0x20:0xffffffff88b2c4e3
stack pointer         = 0x20:0xfffffe884e9f2820
frame pointer        = 0x20:0xfffffe884e9f2840

Caution: zeroes and eights are hard to tell apart from the screenshot I took. 

This is the latest 64 bit TrueOS downloaded and installed on a retired Window XP box.
Dell GX620 Pentium D 3.4 Ghz processor and 1 Gb RAM

**Comment by pkgdemon** [comment] 2017-02-13 00:57
I cannot reproduce this here.  Are you running the Lumina Desktop Environment, or do you have some other DE such as KDE installed?

**Comment by pkgdemon** [comment] 2017-02-13 04:10
Also please run the ```about``` command in a terminal, and provide the output.  Thanks!

**Comment by Unitrunker** [comment] 2017-02-13 04:54
Will do.

**Comment by Unitrunker** [comment] 2017-02-13 07:35
General info:
       Host:................xxxxxxxxxx
       User:................unitrunker
       Uptime:..............4 mins
       FreeBSD kernel ver.:.12.0-CURRENT
       FreeBSD world ver.:..12.0-CURRENT
       FreeBSD git branch:.drm-next
       FreeBSD git rev:....3dbce2a
       TrueOS ver:...........TrueOS-Desktop-201701261715
       Arch:................amd64
       Kernel ident:........GENERIC

I just did a re-install and re-created the exact crash - same register values.

**Comment by Unitrunker** [comment] 2017-02-13 07:54
I also installed this build onto another Dell. This is an Optiplex 760 with an Intel Core 2 Duo 3.0 Ghz and 2 Gb RAM. I get the same general protection trap with the same register values.

In the call stack ... just before the call to kdb_trap() ...
cngrab() at cngrab+0x32/frame 0xfffffe0093b2b5b0

**Comment by pkgdemon** [comment] 2017-02-13 19:42
Thanks.  Could you please also post this output from the ```about``` dump?

```
       Bootloader:.........BSD
       Bootloader type:....BIOS
       CPU:................Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
       CPU cores:..........4       Bootloader:.........BSD
       Bootloader type:....BIOS
       CPU:................Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
       CPU cores:..........4
       Memory (free/avail):30021 / 32768 Mb
       Package set:........STABLE
       Desktop environment:Lumina
       X11 Driver:.........nvidia_drv.so nv_drv.so vesa_drv.so 
```

**Comment by Unitrunker** [comment] 2017-02-14 06:05
Bootloader:..........BSD
Bootloader type:....BIOS
CPU:................Intel(R) Core(TM)2 Duo CPU      E7300  @ 2.66Ghz
CPU Cores:..........2
Memory (free/avail):1355 / 2048 Mb
Package set:........STABLE
Desktop Environment:Lumina
X11 Driver:.........modesetting_drv.so
OSS Driver:.........pcm0: <Analog Devices AD1964A (Analog)> (play/rec) default
WIFI Driver:........

Hope this helps.

**Comment by grahamperrin** [comment] 2017-02-18 07:59
> cngrab() at cngrab+0x32/frame …

In Google search results, all recent matches for that string seem to be associated with `drm-next`. The first two of these five are in a home directory of @kwm81, the others (`pwright@boomers`) might be associated with @nomadlogic: 

- https://people.freebsd.org/~kwm/core.2.txt
- https://people.freebsd.org/~kwm/core.7.txt
- http://pastebin.com/uC4sgegr 
- http://pastebin.com/YB0ZFLGH
- http://pastebin.com/0BDHGEkE

https://github.com/FreeBSDDesktop/freebsd-base-graphics/issues/created_by/nomadlogic nothing open at this time. Seeing the recent closure of KMS-related https://github.com/FreeBSDDesktop/freebsd-base-graphics/issues/108#issuecomment-278422815, and other comments in that issue, I wonder whether a fix for this issue 323 is in the pipeline; not yet in STABLE for TrueOS Desktop.

**Comment by Unitrunker** [comment] 2017-02-18 09:34
Thank you for looking at this.

**Comment by grahamperrin** [comment] 2017-02-26 02:21
@Unitrunker is this issue reproducible with the more recent STABLE distribution of TrueOS Desktop?

**Comment by Unitrunker** [comment] 2017-02-27 06:25
Unknown. I let it upgrade. After reboot, I get a blank screen. I don't know if the new blank screen issue is related or a wholly separate problem. I will burn a fresh ISO and try again.

**Comment by RodMyers** [comment] 2017-04-06 22:53
@Unitrunker is this still an issue with you?

I've been tasked with looking at older issues

thanks

**Comment by Unitrunker** [comment] 2017-04-07 05:52
The fan motor died. The down-side of running old hardware. I have to swap out parts before I can try this again.

**Comment by q5sys** [comment] 2017-04-10 00:34
I tried to replicate this on three separate machines and was unable to.

**Comment by ZackaryWelch** [comment] 2017-08-28 15:13
I was not able to replicate this issue either on a fresh install with the latest build. Has this issue still come up @Unitrunker?

**Comment by Mrt134** [comment] 2017-09-06 13:34
Closed for inactivity. Please comment or reopen if this is still an issue. Thanks!

**Closed by Mrt134** 2017-09-06 13:34 UTC
Labels: info:feedback_needed
