### ISSUE TITLE
PCDM session files accumulating in /

### ISSUE THREAD

**Issue by fjs-github** [trueos/trueos-core#1525] opened 2018-02-01 17:33 UTC
As mentioned by hardcodes on discourse, pcdm-session files/scripts are accumulating in the top-level directory. Maybe that's intended but probably not.

For example:
[11:21:24 - Thu Feb 01 pwd=/]
freds@dfwfreds$ ls -l pcdm*
-rw-r--r--  1 root  wheel  189 Jan 31 09:38 pcdm-session.vt9.a13349
-rw-r--r--  1 root  wheel  189 Jan  9 10:38 pcdm-session.vt9.c42130
-rw-r--r--  1 root  wheel  189 Jan  4 09:53 pcdm-session.vt9.e54314
-rw-r--r--  1 root  wheel  189 Jan 23 09:49 pcdm-session.vt9.E55360
-rw-r--r--  1 root  wheel  189 Jan 18 09:55 pcdm-session.vt9.E66008
-rw-r--r--  1 root  wheel  189 Jan  2 17:08 pcdm-session.vt9.EJ2611
-rw-r--r--  1 root  wheel  189 Jan  8 10:00 pcdm-session.vt9.F27311
-rw-r--r--  1 root  wheel  189 Jan  2 15:08 pcdm-session.vt9.iv2809
-rw-r--r--  1 root  wheel  189 Jan 22 09:41 pcdm-session.vt9.k39554
-rw-r--r--  1 root  wheel  189 Jan  3 12:00 pcdm-session.vt9.Li7494
-rw-r--r--  1 root  wheel  189 Jan 24 09:40 pcdm-session.vt9.M32924
-rw-r--r--  1 root  wheel  189 Jan 30 10:59 pcdm-session.vt9.O89568
-rw-r--r--  1 root  wheel  189 Jan 16 16:33 pcdm-session.vt9.oo1873
-rw-r--r--  1 root  wheel  189 Jan 17 11:46 pcdm-session.vt9.ot2585
-rw-r--r--  1 root  wheel  189 Jan 11 09:47 pcdm-session.vt9.T91906
-rw-r--r--  1 root  wheel  189 Jan 16 16:39 pcdm-session.vt9.tm2611
-rw-r--r--  1 root  wheel  189 Jan 10 09:41 pcdm-session.vt9.U10407
-rw-r--r--  1 root  wheel  189 Jan 17 09:42 pcdm-session.vt9.UZ2363
-rw-r--r--  1 root  wheel  189 Jan 16 10:06 pcdm-session.vt9.V69723
-rw-r--r--  1 root  wheel  189 Feb  1 09:53 pcdm-session.vt9.X92402
-rw-r--r--  1 root  wheel  189 Jan 25 10:02 pcdm-session.vt9.z13498

freds@dfwfreds$ about

===================
General information
===================

boot environment now (N) … 12.0-CURRENT-up-20180116_162736 NR 2018-01-16
       after restart (R) … 12.0-CURRENT-up-20180116_162736 NR 2018-01-16
boot loader …………………………………… BSD
            type ……………………… BIOS
CPU ………………………………………………………… AMD Phenom(tm) II X4 955 Processor
    number of cores ……………… 4
host ……………………………………………………… dfwfreds.redacted.com
memory ………………………………………………… 10240 MB available, 8410 MB free
OS git branch ……………………………………………………………………………………… trueos-stable-17.12
OS git revision ………………………………………………………………………………… d26791952
OS kernel build time ………………………………………………………… Sat 2017 Dec 9 18:10:09 UTC
OS kernel identity …………………………………………… (uname -i) GENERIC
OS platform (architecture) ……………………… (uname -m) amd64
OS release level ………………………………………………… (uname -r) 12.0-CURRENT
OS version and patch level …… (freebsd-version) 12.0-CURRENT
TrueOS package set ………………… STABLE
TrueOS version …………………………… TrueOS-Desktop-201712111405
uptime ………………………………………………… 14 days, 23:44
user  …………………………………………………… freds

More (TrueOS Desktop):

    desktop environment …… Lumina
    sound card driver ………… pcm0: <Realtek ALC892 (Rear Analog 7.1/2.0)> (play/rec) default
    wireless driver ……………… 
    X11 drivers ………………………… nvidia_drv.so

**Comment by q5sys** [comment] 2018-02-02 02:08
Thanks for the ticket!  I'm going to closing this as it is a duplicate of: https://github.com/trueos/trueos-core/issues/1524

**Closed by q5sys** 2018-02-02 02:08 UTC
