### ISSUE TITLE
TrueOS-Desktop hangs during boot (for install)

### ISSUE THREAD

**Issue by Vanhecke** [trueos/trueos-core#199] opened 2016-12-11 19:54 UTC
I'm trying to install TrueOS-Desktop-2016-10-28-x64 on my Thinkpad x230.

I downloaded TrueOS-Desktop-2016-10-28-x64-USB.img  and wrote it to USB,
after a few seconds of trueos booting up it stays stuck at the output of ifconfig.

Any ideas?

**Comment by pkgdemon** [comment] 2016-12-11 20:46
Can you take a pic, and attach a screenshot?

**Comment by Vanhecke** [comment] 2016-12-11 22:34
![I hope this helps](https://cloud.githubusercontent.com/assets/3396438/21083890/15ff7852-bffa-11e6-90cc-83d1329a09b1.JPG)

**Comment by pkgdemon** [comment] 2016-12-12 12:30
If I had to guess it looks like it's hanging up on loading the wifi device.  Let me discuss with the other devs today to see if there are any options to get around this.

**Comment by frankurcrazy** [comment] 2016-12-12 16:43
having the same problem here with ASUS UX31A

**Comment by grahamperrin** [comment] 2016-12-12 19:50
I had the same problem … maybe just once, a few weeks ago but (sorry) I can't recall details of the test environment.

**Comment by Vanhecke** [comment] 2016-12-13 12:25
@pkgdemon 
The wifi card should work with the iwn driver (it does so on openbsd).
I tried booting with the "hardware switch" off but it didn't change much.

Would booting with wired networking help?

**Comment by wost0k** [comment] 2016-12-15 21:46
hi,

i had the same problem - then i deactived wlan via bios and used lan. after the installation i activated wlan. .)

**Comment by Vanhecke** [comment] 2016-12-15 23:44
@wost0k Thanks for the suggestion but I think it will be easier for me to disable it in trueos.
Im running seabios.

**Comment by NaomasaMaruyama** [comment] 2016-12-17 02:34
I have the same problem, too.  Lenovo(ThinkPad) X230s have "Legacy boot/UEFI boot" switching ability, and I see this problem in both boot mode.  Note that you have to update UEFI bios, or else you will see more nasty screen than the  pic above when UEFI booted.  The latest UEFI bios is version 2.67 of Sep. 26th, 2016, I believe.  See lenovo support site.

**Comment by NaomasaMaruyama** [comment] 2016-12-17 07:06
I tested TrueOS-Desktop-2016-12-15-x64-USB on my Lenovo ThinkPad X230.  In both legacy and UEFI boot mode, I don't see any similar thing. I believe its a time to close this issue.

**Comment by grahamperrin** [comment] 2016-12-17 07:13
[Laptops-and-netbooks :: ThinkPad-X-Series-laptops :: ThinkPad-X230 - Lenovo Support](http://support.lenovo.com/gb/en/products/Laptops-and-netbooks/ThinkPad-X-Series-laptops/ThinkPad-X230) – /gb/ product support page

[Lenovo ThinkPad X230 Laptop Review | Best Business Notebooks](http://www.laptopmag.com/reviews/laptops/lenovo-thinkpad-x230) (2012-05-31) 

> … right side are a micro SD Card reader, a USB 2.0 port that can charge devices while the system's asleep, a headphone jack and an Ethernet port, something you won't find on some ultraportables. On the left side of the chassis sit two USB 3.0 ports, a VGA port, DisplayPort, and an ExpressCard/34 slot. There's also a hardware Wi-Fi on/off …

– so the bug might be easily worked around, but it will be good to have a fix. Or at least an understanding of things. 

@Vanhecke 

What speed is the USB flash drive: 2.0 or 3.0?

When the bug bites, is there any other wired or wireless peripheral device? Or is the USB flash drive the sole peripheral, and if so: in which port? 

If you use an external optical drive, no other wired or wireless peripheral, with TrueOS-Desktop-2016-12-15-x64-DVD.iso then is the bug reproducible?

----

Me: 

> I can't recall details of the test environment.

Gut feeling. I'll test the most recently pushed .img with an HP EliteBook 850 G2 in legacy mode.

**Comment by grahamperrin** [comment] 2016-12-17 07:16
Postscript (comments crossed paths)

> tested TrueOS-Desktop-2016-12-15-x64-USB

– thanks to @NaomasaMaruyama and so, I'll **not** test test the most recently pushed .img with an HP EliteBook 850 G2 in legacy mode, unless developers require it.

**Comment by NaomasaMaruyama** [comment] 2016-12-18 03:45
@grahamperrin 
> Laptops-and-netbooks :: ThinkPad-X-Series-laptops :: ThinkPad-X230 - Lenovo Support – /gb/ product support page

> Lenovo ThinkPad X230 Laptop Review | Best Business Notebooks (2012-05-31)

That's not I meant.  See [BIOS Update Utility for Windows 10 (64-bit), 8.1 (32-bit, 64-bit), 8 (32-bit, 64-bit), 7 (32-bit, 64-bit), XP - ThinkPad X230 Tablet and X230i Tablet - Lenovo Support ](http://support.lenovo.com/us/en/downloads/ds029683).

**Comment by Vanhecke** [comment] 2016-12-18 20:09
@grahamperrin 
I don't understand why you are quoting this article?
The only device I plugged in was a USB2.0 pendrive, and I tried the USB2.0 and 3.0 ports.

@NaomasaMaruyama 
Thanks for the suggestion but as I said I'm not running the Lenovo bios/firmware.

**Comment by grahamperrin** [comment] 2016-12-18 20:29
The quote was to help visualise the hardware; to know its device capabilities.

**Comment by q5sys** [comment] 2016-12-18 21:00
Vanhecke,
are you still unable to install?  Did you try turning the wifi off initally in the bios to see if you can install that way?

**Comment by grahamperrin** [comment] 2016-12-18 21:25
Also/alternatively the (quoted) hardware Wi-Fi on/off. If switched off at that level, then can the OS be installed?

**Comment by Vanhecke** [comment] 2016-12-19 16:27
@q5sys 
I don't have any kind of "live" bios settings menu.
Removing the wireless card physically is probably the fastest option for me,
but its a bit much just to try out the OS.

@grahamperrin 
> I tried booting with the "hardware switch" off but it didn't change much.

**Comment by q5sys** [comment] 2016-12-19 16:50
@Vanhecke 
Since you're using a non standard BIOS, i don't think there is much we are going to be able to do.  If the hardware itself is hanging the boot process due to the BIOS, that's very much out of scope for us.  It'd be nice to be able to support alternative BIOS options, but I realistically don't believe its possible.  We know that the standard BIOS in the Lenovo x230s works fine. If you're not willing to remove the hardware to test further, which is understandable why you wouldnt want to, then we've hit the end of the road of what we are going to be able to do.  Sorry.  I'm going to go ahead and close this ticket now, since I dont think there is anything we're going to be able to do.  If something comes up in the future, and we can make headway on it, we'll open the ticket back up.

**Closed by q5sys** 2016-12-19 16:50 UTC

**Comment by Vanhecke** [comment] 2016-12-19 16:53
FYI - Windows 7, Windows 10, Linux (Debian Stable) and OpenBSD can do this.

**Comment by NaomasaMaruyama** [comment] 2016-12-20 00:15
@Vanhecke 
>I tried booting with the "hardware switch" off but it didn't change much.

Sorry, I already erased "TrueOS-Desktop-2016-10-28-x64" image from my disks, so I can not do the same experiment again, but when I boot with "TrueOS-Desktop-2016-12-15-x64-USB", iwn0 device is probed even if I switch off the wireless LAN by the "hardeware switch" in the left of x230.  In the contrast, when I disable the Wireless LAN device by BIOS menu, iwn0 device is not probed.  I can see this by the dmesg.  So "hardware switch off" approach will never give a solution to this.  Taking this info account, I think the way @wost0k took is a clever way to walk around this issue before Dec. 14th:
 
>i had the same problem - then i deactived wlan via bios and used lan. after the installation i activated wlan. .)

But you are saying you can not de-activate the Wireless LAN device because you are using SeaBIOS!
Really? Is the SeaBIOS such a poor software?  Why don't you through away such a poor software? The standard Lenovo BIOS can run Windows 7, Windows 10, Linux (Debian Stable) and OpenBSD.
Why don't you try TrueOS-Desktop-2016-12-15-x64-USB?

**Comment by uMtMu** [comment] 2018-05-03 14:09
I stuck at same point with TrueOS-Desktop-18.03-x64-USB.img on Acer E3-112-C37C Intel Celeron N2840 yesterday. I will try with disabling wifi.
