### ISSUE TITLE
after appcafe install of virtualbox additions, desktop will not start

### ISSUE THREAD

**Issue by kahjs2007** [trueos/trueos-core#44] opened 2016-09-02 20:59 UTC
To reproduce:

virtual box host is 4.3.38_ose r106717, on pcbsd 10.3

Install ( or update existing pcbsd 10.3 vm) into new vm.

Use appcafe to install virtualbox additions

reboot

desktop manager tries to start, crashes back to console, loop between desktop manager attemping to start and console ...

**Comment by kahjs2007** [comment] 2016-09-02 21:15
TrueOS-Desktop-2016-08-31-x64-DVD.iso  used for installs.

**Comment by pkgdemon** [comment] 2016-09-04 20:51
Please send pcbsd bugs to bugs.pcbsd.org.  This is for TrueOS.

**Comment by xzovy** [comment] 2016-09-04 22:29
This is not a PCBSD bug, please reopen it. This happens in TrueOS Desktop installs OR upgrades from PCBSD. References to PCBSD in the intial report were to the host OS and to upgrading FROM PCBSD. User also stated that it happens on fresh installs with the 8-31 release of TrueOS. This bug also happens for me with TrueOS guests on Linux hosts.

**Comment by pkgdemon** [comment] 2016-09-05 00:01
Sorry for closing.  I couldn't find any language about TrueOS being used in the ticket when I reviewed it.  I will reopen for you.  Just FYI we are aware that virtualbox-ose-additions have been broken with TrueOS for some time.

**Comment by pkgdemon** [comment] 2016-09-05 01:11
Would you be able to check for the precense of /etc/X11/xorg.conf, and attach it's contents here if you have one?

**Comment by xzovy** [comment] 2016-09-05 01:44
I have included the xorg configs and Xorg log files from before and after the installation of the virtualbox-ose-additions package. It should be noted that removing the package does not resolve the issue.

[xorg.conf-before.txt](https://github.com/trueos/trueos-core/files/454251/xorg.conf-before.txt)
[Xorg.0.log-before.txt](https://github.com/trueos/trueos-core/files/454252/Xorg.0.log-before.txt)
[Xorg.0.log-after.txt](https://github.com/trueos/trueos-core/files/454254/Xorg.0.log-after.txt)
[xorg.conf-after.txt](https://github.com/trueos/trueos-core/files/454253/xorg.conf-after.txt)

**Comment by pkgdemon** [comment] 2016-09-05 01:51
Ok try this:

Boot into single user mode by pressing 2 at the loader menu.
Type kldload vboxdrv
Type exit

**Comment by xzovy** [comment] 2016-09-05 01:55
To be clear, this should be done before installing the package, after the package, after reinstalling the package? I have VMs in several states to test this issue.

**Comment by pkgdemon** [comment] 2016-09-05 01:58
You will want to do this anytime after the pacakge is installed.

**Comment by xzovy** [comment] 2016-09-05 02:01
Output of "kldload vboxdrv": "kldload: can't load vboxdrv: No such file or directory"

To be clear, the issue is with running TrueOS as a GUEST not as a HOST. Loading the vboxdrv module should only apply to hosts, iirc.

**Comment by pkgdemon** [comment] 2016-09-05 02:06
Correct.  I was thinking that module also loaded with:

vboxguest_enable="YES"
vboxservice_enable="YES"

Which you may need to add to rc.conf.  We removed trueos-meta-virtualbox* ports.  For several reasons.  A big reason is that I discovered an issue where install virtualbox on the host would crash systems, and not allow even single user mode for recovery without unsetting modules at the loader prompt.  There are other ways to fix vboxdrv loading if needed with rc.conf.

**Comment by pkgdemon** [comment] 2016-09-05 02:13
I notice your "before" xorg.conf shows the VESA driver in use.

**Comment by xzovy** [comment] 2016-09-05 02:17
I added those lines to my /etc/rc.conf and it made no difference.

Yes, the reason my "before" xorg.conf includes VESA is another bug, in order to get a graphical install in vbox I need to use that option during install time.

**Comment by pkgdemon** [comment] 2016-09-05 02:23
Yeah it's only recently virtualbox-ose-additions started building again.  You could try slimming down your /etc/x11/xorg.conf to just:

Section "Device"
        Identifier  "Card0"
        Driver      "vboxvideo"
EndSection

We have also had some issues with our older xorg.conf templates not being compatible with the new xorg we pulled in.  This would tell us if that was the issue.

**Comment by pkgdemon** [comment] 2016-09-06 18:26
Ok we found something today.  We had to enable 3D support for the guest.  Can you try this?  We determined this from reviewing logs that when virtualbox-guest-additions is being installed it is breaking all support for any video hardware without opengl acceleration.

**Comment by kahjs2007** [comment] 2016-09-24 17:19
Guest still loops after enabling 3d support.

**Comment by kahjs2007** [comment] 2016-09-24 18:39
Same issue with a clean install of 2016-09-20, with or without 3D.

**Comment by pkgdemon** [comment] 2016-09-26 17:23
I can confirm all works again in our latest set of packages.  I will keep this open until we push them.  It won't be working in the installer right away but it will work again post install.

**Comment by pkgdemon** [comment] 2016-09-30 11:11
We were able to resolve this by disabling opengl support in the virtualbox-ose-additions port.  I was also able to fix support in the installer by adding virtualbox to our auto-detection routine where it starts the guest service, and uses the appropriate xorg configuration.  The latest ISO's, and packages include the fixes.

**Closed by pkgdemon** 2016-09-30 11:11 UTC
